### ISSUE TITLE
Streamline passing rolls between player and GM

### ISSUE THREAD

**Issue by aMediocreDad** [aMediocreDad/litm#43]
- When passing a roll to the GM allow player to skip GM moderation (in case of websocket failure or moderation not being needed).
- Show buttons at all times.

**Comment by AlexGonz1994** [comment]
Would there be a way to add back the roll dice screen like in the image? Even if only for the MC. Being able to select weakness tags as the MC on the fly when I feel the apply would be great instead of having to tell my players to pick them especially since some can be a bit quick on pressing roll before I even have the chance to suggest a weakness.
![image-11](https://github.com/aMediocreDad/litm/assets/61664927/3e94a5f5-0d85-412f-b617-efd5b523877d)

**Comment by aMediocreDad** [comment]
> Would there be a way to add back the roll dice screen like in the image? Even if only for the MC. Being able to select weakness tags as the MC on the fly when I feel the apply would be great instead of having to tell my players to pick them especially since some can be a bit quick on pressing roll before I even have the chance to suggest a weakness.

It already works like that:

https://github.com/aMediocreDad/litm/assets/9851733/8bda4bd6-5323-46c6-bc62-d65b18651e1f
